spring.application.name=Fatcat
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

server.servlet.context-path=/api
management.endpoints.web.exposure.include=health

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}